export const PUJA_SERVICE_OPTIONS = [
  'Marriage Puja',
  'Griha Pravesh',
  'Satyanarayan Katha',
  'Birthday Puja',
  'Sunderkand Path',
  'Business Opening',
  'Havan',
  'Navratri Puja',
  'Bhagwat Katha',
  'Shradh',
  'Rudrabhishek',
  'Mundan',
  'Mahamrityunjaya Jaap',
  'Ganesh Puja',
  'Lakshmi Puja',
  'Saraswati Puja',
  'Durga Puja',
  'Kali Puja',
  'Shiv Puja',
  'Vishnu Puja',
  'Ram Katha',
  'Shiv Mahapuran Katha',
  'Akhand Ramayan Path',
  'Hanuman Chalisa Path',
  'Grah Shanti Puja',
  'Navgraha Puja',
  'Vastu Shanti Puja',
  'Bhoomi Pujan',
  'Shilanyas Puja',
  'Office Puja',
  'Shop Opening Puja',
  'Vehicle Puja',
  'Factory Puja',
  'Lakshmi Kuber Puja',
  'Dhanteras Puja',
  'Ayudha Puja',
  'Namkaran Sanskar',
  'Annaprashan Sanskar',
  'Vidyarambh Sanskar',
  'Janeu Sanskar',
  'Engagement Puja',
  'Wedding Anniversary Puja',
  'Baby Shower Puja',
  'Kaal Sarp Dosh Puja',
  'Mangal Dosh Puja',
  'Pitra Dosh Puja',
  'Shani Shanti Puja',
  'Rahu Ketu Shanti Puja',
  'Chandi Path',
  'Gayatri Havan',
  'Chandi Havan',
  'Sudarshan Havan',
  'Putra Kameshti Yagya',
  'Antyeshti Sanskar',
  'Terahvi Kriya',
  'Asthi Visarjan',
  'Narayan Bali Puja',
  'Tripindi Shradh',
] as const;

export type PujaServiceName = (typeof PUJA_SERVICE_OPTIONS)[number];

export const HOME_PUJA_CATEGORIES = [
  { id: '1', label: 'Marriage Puja', emoji: '💍', bg: '#FEE2E2', color: '#DC2626' },
  { id: '2', label: 'Griha Pravesh', emoji: '🏠', bg: '#DBEAFE', color: '#2563EB' },
  { id: '3', label: 'Satyanarayan Katha', emoji: '📖', bg: '#FCE7F3', color: '#DB2777' },
  { id: '4', label: 'Havan', emoji: '🔥', bg: '#FFEDD5', color: '#EA580C' },
  { id: '5', label: 'Rudrabhishek', emoji: '🕉️', bg: '#E0E7FF', color: '#4338CA' },
  { id: '6', label: 'Sunderkand Path', emoji: '📿', bg: '#F3E8FF', color: '#9333EA' },
  { id: '7', label: 'More', emoji: '⊞', bg: '#FEF9C3', color: '#CA8A04' },
] as const;

const CATEGORY_STYLE_LOOKUP: Record<string, { emoji: string; bg: string }> = {
  'Marriage Puja': { emoji: '💍', bg: '#FEE2E2' },
  'Griha Pravesh': { emoji: '🏠', bg: '#DBEAFE' },
  'Satyanarayan Katha': { emoji: '📖', bg: '#FCE7F3' },
  'Birthday Puja': { emoji: '🎂', bg: '#FCE7F3' },
  'Sunderkand Path': { emoji: '📿', bg: '#F3E8FF' },
  'Business Opening': { emoji: '🏢', bg: '#E0F2FE' },
  Havan: { emoji: '🔥', bg: '#FFEDD5' },
  'Navratri Puja': { emoji: '🪔', bg: '#FEF3C7' },
  'Bhagwat Katha': { emoji: '📚', bg: '#EDE9FE' },
  Shradh: { emoji: '🙏', bg: '#F3F4F6' },
  Rudrabhishek: { emoji: '🕉️', bg: '#E0E7FF' },
  Mundan: { emoji: '👶', bg: '#DCFCE7' },
  'Mahamrityunjaya Jaap': { emoji: '📿', bg: '#E0E7FF' },
  'Ganesh Puja': { emoji: '🐘', bg: '#FEF9C3' },
  'Lakshmi Puja': { emoji: '🪷', bg: '#FEF3C7' },
  'Saraswati Puja': { emoji: '🎵', bg: '#E0F2FE' },
  'Durga Puja': { emoji: '🦁', bg: '#FCE7F3' },
  'Kali Puja': { emoji: '🔱', bg: '#FEE2E2' },
  'Shiv Puja': { emoji: '🔱', bg: '#E0E7FF' },
  'Vishnu Puja': { emoji: '🪷', bg: '#DBEAFE' },
};

const FALLBACK_STYLES = [
  { emoji: '🙏', bg: '#FFF7ED' },
  { emoji: '🪔', bg: '#FEF3C7' },
  { emoji: '📿', bg: '#F3E8FF' },
  { emoji: '🕉️', bg: '#E0E7FF' },
];

export function getPujaServiceStyle(name: string, index: number) {
  if (CATEGORY_STYLE_LOOKUP[name]) return CATEGORY_STYLE_LOOKUP[name];
  return FALLBACK_STYLES[index % FALLBACK_STYLES.length];
}
