/** ApnaAcharya Pandit — spiritual saffron & maroon brand palette */
export const DashboardColors = {
  primary: '#FF6B00',
  primaryDark: '#E65100',
  primaryLight: '#FFB366',
  maroon: '#6B1515',
  maroonDark: '#4A0E0E',
  maroonLight: '#8B2525',
  saffron: '#FF8C00',
  gold: '#D4A017',
  goldLight: '#F5D76E',
  cream: '#FFF8F0',
  creamDark: '#F5E6D3',
  success: '#2E7D32',
  danger: '#B71C1C',
  purple: '#9333EA',
  blue: '#1D4ED8',
  text: '#3D1515',
  textMuted: '#7A4A4A',
  textLight: '#A67B7B',
  background: '#FFFBF5',
  card: '#FFFFFF',
  border: '#F0DCC8',
  borderGold: '#E8C878',
  orangeBg: '#FFF0E0',
  greenBg: '#ECFDF5',
  purpleBg: '#F3E8FF',
  yellowBg: '#FFFBEB',
  yellowBadge: '#D4A017',
  trustBg: '#FFF5EB',
};

export const Brand = {
  name: 'ApnaAcharya',
  tagline: 'Serve with Devotion',
  greeting: 'Namaste',
};
