module.exports = [
  'Marriage Puja',
  'Griha Pravesh',
  'Satyanarayan Katha',
  'Birthday Puja',
  'Sunderkand Path',
  'Business Opening',
  'Havan',
  'Navratri Puja',
  'Bhagwat Katha',
  'Shradh',
  'Rudrabhishek',
  'Mundan',
  'Mahamrityunjaya Jaap',
  'Ganesh Puja',
  'Lakshmi Puja',
  'Saraswati Puja',
  'Durga Puja',
  'Kali Puja',
  'Shiv Puja',
  'Vishnu Puja',
  'Ram Katha',
  'Shiv Mahapuran Katha',
  'Akhand Ramayan Path',
  'Hanuman Chalisa Path',
  'Grah Shanti Puja',
  'Navgraha Puja',
  'Vastu Shanti Puja',
  'Bhoomi Pujan',
  'Shilanyas Puja',
  'Office Puja',
  'Shop Opening Puja',
  'Vehicle Puja',
  'Factory Puja',
  'Lakshmi Kuber Puja',
  'Dhanteras Puja',
  'Ayudha Puja',
  'Namkaran Sanskar',
  'Annaprashan Sanskar',
  'Vidyarambh Sanskar',
  'Janeu Sanskar',
  'Engagement Puja',
  'Wedding Anniversary Puja',
  'Baby Shower Puja',
  'Kaal Sarp Dosh Puja',
  'Mangal Dosh Puja',
  'Pitra Dosh Puja',
  'Shani Shanti Puja',
  'Rahu Ketu Shanti Puja',
  'Chandi Path',
  'Gayatri Havan',
  'Chandi Havan',
  'Sudarshan Havan',
  'Putra Kameshti Yagya',
  'Antyeshti Sanskar',
  'Terahvi Kriya',
  'Asthi Visarjan',
  'Narayan Bali Puja',
  'Tripindi Shradh',
];
